### ISSUE TITLE
Add a flag to ignore when original package isn't installed

### ISSUE THREAD

**Issue by Jackenmen** [iuscommunity/yum-plugin-replace#11]
Would be nice if this plugin would allow (by using a flag) to ignore that original package isn't installed and just install the new package in such case

**Comment by carlwgeorge** [comment]
This plugin hasn't been actively developed in many years.  Better options exist now, which IUS recommends on our [usage](https://ius.io/usage) page.

- `yum shell`
- `yum swap`
- `dnf --allowerasing install`

I'll go as far as declaring this plugin deprecated.  I'll archive the repo to make that status clear.
