### ISSUE TITLE
replace php56u --> php70u not working?

### ISSUE THREAD

**Issue by futureweb** [iuscommunity/yum-plugin-replace#7]
Hi,
I'm trying to replace php56u with php70u - but it's not really working?! :-/

`CT-378-bash-4.2# yum replace php56u --replace-with php70u
Loaded plugins: fastestmirror, protectbase, replace
Replacing packages takes time, please be patient...
Loading mirror speeds from cached hostfile
Excluding mirror: gd.tuwien.ac.at
 * base: mirror.nextlayer.at
 * epel: mirror.karneval.cz
Excluding mirror: gd.tuwien.ac.at
 * extras: mirror.nextlayer.at
 * ius: mirror.amsiohosting.net
Excluding mirror: gd.tuwien.ac.at
 * updates: mirror.nextlayer.at
0 packages excluded due to repository protections
Error: No Package Matching php70u`

Any ideas on this?

thx
Andreas Schnederle-Wagner

**Comment by b-harper** [comment]
Hey @futureweb,

Thanks for taking the time to submit this issue.  Try the following command:

```
# yum replace php56u-common --replace-with php70u-common
```

The naming scheme of PHP packages is a little strange.  The main 'php' or 'php56u' package is really the mod_php httpd module and not the main package.  We tired something different with our php70u packages and now have a mod_php70u package.

**Comment by futureweb** [comment]
that did the Trick - thx
