### ISSUE TITLE
Can't seem to load from script

### ISSUE THREAD

**Issue by LewisR** [iuscommunity/yum-plugin-replace#9]
On OS/2, we have a graphical yum frontend (Arca Noae Package Manager). Most yum functions are called via python scripts. While other plugins (even TYPE_INTERACTIVE) seem perfectly happy to load this way, replace does not.

Here's a test script:

#! /usr/bin/python -tt

import os
import sys
import time
import re
import yum
import logging
import platform

yb = yum.YumBase()
yb.setCacheDir()
yb.conf.cache = os.geteuid() != 0

print yb.plugins._plugins

Other plugins report loading.

Any thoughts on why this is and how we might work around it?

**Comment by b-harper** [comment]
Hey @LewisR,

I am not sure how much we might be able to help.  Lets start with some basic version information about your setup:

OS/2:
python:
yum:
rpm:

Are there any warning and/or errors messages?  What is the output of that script when you run it?

**Comment by andytson** [comment]
It's been a while since I've worked on the code, but I seem to remember comparing it to other modules and seeing it had some backwards compatibility code in to support EL5 plugin api.

I have a feeling removing that support will fix it.

Andy

**Comment by LewisR** [comment]
Interesting, Andy.

I can reproduce the condition under OS/2 Warp 4.52, eComStation 2.1, and ArcaOS 5.0.1.

python: 2.7.6
yum: 3.4.3
rpm: 4.13.0

The script should output something like:

Loading "replace" plugin
Loading "versionlock" plugin
Running "config" handler for "replace" plugin
Running "config" handler for "versionlock" plugin

Instead, it looks like replace is just not loaded, so I only see references to versionlock.

On my running system, where I have more plugins loaded, I can see that replace is not the only one which behaves this way:

[c:\] yum foo
Loading "downloadonly" plugin
Loading "replace" plugin
Loading "verify" plugin
Loading "versionlock" plugin
Running "config" handler for "downloadonly" plugin
Running "config" handler for "replace" plugin
Running "config" handler for "verify" plugin
Running "config" handler for "versionlock" plugin
Config time: 0.166
Yum Version: 3.4.3
COMMAND: yum foo
Installroot: /@unixroot
No such command: foo. Please use J:\USR\BIN\YUM --help

vs:

[c:\] set PYTHONPATH=j:/usr/share/yum-cli
[c:\] python yum_plug.py
Loading "versionlock" plugin
Running "config" handler for "versionlock" plugin
Config time: 1.185
{'versionlock': (<module 'versionlock' from '/@unixroot/usr/lib/yum-plugins/vers
ionlock.pyc'>, <ConfigParser.ConfigParser instance at 0x205bf8ac>)}

So, I wonder what downloadonly and verify have in common with replace? I should have checked before, perhaps, but my main test system is naturally limited to just the plugins we're attempting to manage.

**Comment by b-harper** [comment]
@LewisR,

Thanks for the additional information.  Here is the versions and output for EL6 and EL7:

EL6:
<details>

OS: CentOS 6.9

python: 2.6.6

yum: 3.2.29

rpm: 4.8.0

```
$ python
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import sys
>>> import time
>>> import re
>>> import yum
>>> import logging
>>> import platform
>>> yb = yum.YumBase()
>>> yb.setCacheDir()
Plugin "replace" can't be imported
Loaded plugins: fastestmirror
True
>>> yb.conf.cache = os.geteuid() != 0
>>> print yb.plugins._plugins
{'fastestmirror': (<module 'fastestmirror' from '/usr/lib/yum-plugins/fastestmirror.pyc'>, <iniparse.compat.RawConfigParser object at 0x1e0a590>)}
>>> 
```

``` 
$ sudo yum replace
Loaded plugins: fastestmirror, replace, security
Replacing packages takes time, please be patient...
Error: Must specify a package to be replaced (i.e yum replace pkg --replace-with pkgXY)

$ sudo yum replace rsync --replace-with rsync31u
Loaded plugins: fastestmirror, replace, security
Replacing packages takes time, please be patient...
Loading mirror speeds from cached hostfile
 * elrepo: mirror.rackspace.com

WARNING: Unable to resolve all providers: ['config(rsync)']

This may be normal depending on the package.  Continue? [y/N] y
Resolving Dependencies
--> Running transaction check
---> Package rsync.x86_64 0:3.0.6-12.el6 will be erased
---> Package rsync31u.x86_64 0:3.1.2-2.ius.centos6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================
 Package Arch   Version             Repository                                Size
===================================================================================
Installing:
 rsync31u
         x86_64 3.1.2-2.ius.centos6 ius                                      367 k
Removing:
 rsync   x86_64 3.0.6-12.el6        @anaconda-CentOS-201410241409.x86_64/6.6 682 k

Transaction Summary
===================================================================================
Install       1 Package(s)
Remove        1 Package(s)

Total download size: 367 k
Is this ok [y/N]: y
Downloading Packages:
rsync31u-3.1.2-2.ius.centos6.x86_64.rpm                     | 367 kB     00:00     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : rsync31u-3.1.2-2.ius.centos6.x86_64                             1/2 
  Erasing    : rsync-3.0.6-12.el6.x86_64                                       2/2 
  Verifying  : rsync31u-3.1.2-2.ius.centos6.x86_64                             1/2 
  Verifying  : rsync-3.0.6-12.el6.x86_64                                       2/2 

Removed:
  rsync.x86_64 0:3.0.6-12.el6                                                      

Installed:
  rsync31u.x86_64 0:3.1.2-2.ius.centos6                                            

Complete!
```
</details>

EL7:
<details>

OS: CentOS 7.3.1611

python: 2.7.5

yum: 3.4.3

rpm: 4.11.3

```
$ python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import sys
>>> import time
>>> import re
>>> import yum
>>> import logging
>>> import platform
>>> yb = yum.YumBase()
>>> yb.setCacheDir()
Plugin "replace" can't be imported
Loaded plugins: auto-update-debuginfo, fastestmirror, langpacks
True
>>> yb.conf.cache = os.geteuid() != 0
>>> print yb.plugins._plugins
{'fastestmirror': (<module 'fastestmirror' from '/usr/lib/yum-plugins/fastestmirror.pyc'>, <iniparse.compat.RawConfigParser object at 0x7f0703a7d8d0>), 'auto-update-debuginfo': (<module 'auto-update-debuginfo' from '/usr/lib/yum-plugins/auto-update-debuginfo.pyc'>, <iniparse.compat.RawConfigParser object at 0x7f0703a7d890>), 'langpacks': (<module 'langpacks' from '/usr/lib/yum-plugins/langpacks.pyc'>, <iniparse.compat.RawConfigParser object at 0x7f0703a7db90>)}
>>> 
```

```
$ sudo yum replace
Loaded plugins: auto-update-debuginfo, fastestmirror, langpacks, replace
Replacing packages takes time, please be patient...
Error: Must specify a package to be replaced (i.e yum replace pkg --replace-with pkgXY)

$ sudo yum replace rsync --replace-with rsync31u
Loaded plugins: auto-update-debuginfo, fastestmirror, langpacks, replace
Replacing packages takes time, please be patient...
Loading mirror speeds from cached hostfile

WARNING: Unable to resolve all providers: ['config(rsync)']

This may be normal depending on the package.  Continue? [y/N] y
Resolving Dependencies
--> Running transaction check
---> Package rsync.x86_64 0:3.0.9-17.el7 will be erased
---> Package rsync31u.x86_64 0:3.1.2-2.ius.centos7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================
 Package         Arch          Version                      Repository        Size
===================================================================================
Installing:
 rsync31u        x86_64        3.1.2-2.ius.centos7          ius              385 k
Removing:
 rsync           x86_64        3.0.9-17.el7                 @anaconda        732 k

Transaction Summary
===================================================================================
Install  1 Package
Remove   1 Package

Total download size: 385 k
Is this ok [y/d/N]: y
Downloading packages:
rsync31u-3.1.2-2.ius.centos7.x86_64.rpm                     | 385 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : rsync31u-3.1.2-2.ius.centos7.x86_64                             1/2 
  Erasing    : rsync-3.0.9-17.el7.x86_64                                       2/2 
  Verifying  : rsync31u-3.1.2-2.ius.centos7.x86_64                             1/2 
  Verifying  : rsync-3.0.9-17.el7.x86_64                                       2/2 

Removed:
  rsync.x86_64 0:3.0.9-17.el7                                                      

Installed:
  rsync31u.x86_64 0:3.1.2-2.ius.centos7                                            

Complete!
```
</details>


The plugin works, but does not get imported within your test.

Before we go any further, I am curious if there is a need for this plugin. It was created to solve a very specific use case.  IUS creates newer packages (that are provided by Red Hat) in such a way that a simple ```yum upgrade``` would not work to upgrade from stock packages to IUS packages.  We were looking for an easier approach then using [yum shell][0].  Do those OSes have third party repositories that work like IUS?  If not, it may not make sense to try to get yum-plugin-replace working.  I think some additional UI elements would be needed based on the screenshots I was able to find.  

Also note, [dnf][1], yum's replacement, has a ```--allowerasing``` feature that kind does the same thing as yum-plugin-replace.

[0]: https://ius.io/Usage/#safe-replacement-packages
[1]: http://dnf.baseurl.org/

**Comment by LewisR** [comment]
Very interesting, and very good questions, indeed. Here's some more information:

When the maintainers of the vast majority of ported *nix apps for OS/2 originally decided to package them as rpm, the base arch selected was i386. Since that time, i386 has been deprecated, and the base arch is i686, with pentium4 being the alternative optimization.

Unfortunately, this shift left us (the OS/2 community, at large) with a collection of "orphaned" i386 packages. In addition, some packages, aside from moving to i686/pentium4 builds, changed names, making it more difficult to upgrade them in place. This condition was/is further complicated by the now *nix-like dependency problems (can't uninstall <blah> because it is needed by <blah-blah>. This is where the replace plugin really shines in the vast majority of cases.

In my own testing, I have taken a base install of about 50 packages, all i686, changed platform to pentium4, and have replaced them all - in place, providing a better match for my hardware.

Another use case is possible conflicts between the "standard" repos (Netlabs release and experimental, netlabs-rel and netlabs-exp, respectively) and Arca Noae's own repositories (arcanoae-rel, arcanoae-exp, arcanoae-sub, and the on-disc repo for ArcaOS). A quick example here is GPL GhostScript as distributed with ArcaOS in its on-disc repo and the newer GhostScript available from netlabs-rel (which Arca Noae cannot distribute with ArcaOS, as ArcaOS is a commercial product, and we - Arca Noae - would need a commercial distribution license to include the latest GhostScript). Replacing one with the other after-the-fact is the easiest way to get a current GhostScript onto the system.

On Linux, I'm a SuSE guy, so zypper has always been my choice. However, I'm not the maintainer of yum on the OS/2 platform, and I don't get to decide that single-handedly. I suppose at some point, we'll switch to dnf, but I haven't heard a timeline for that change, as yet.

[Arca Noae](https://www.arcanoae.com), my company, which provides the GPL tool, Arca Noae Package Manager ([ANPM](https://www.arcanoae.com/resources/downloadables/arca-noae-package-manager/)), sits as a graphical front end to yum (which, when it debuted on the OS/2 scene was met with much disdain from many long-time OS/2 users as being too "un-OS/2"). ANPM provides a more consistent OS/2 feel for all of this, and we are also working to add support for our other main package manager, WarpIN, handling possible installation conflicts between packages of both worlds (though that is not where the replace plugin comes into play; I only mention that for some additional perspective).

Unfortunately, SeaMonkey is not being cooperative here on github with the handy markdown menu today, so I hope my links come through as intended (even preview is not working for me). Apologies in advance if any of that is truly munged.

**Comment by b-harper** [comment]
@LewisR,

It would appear that there is a need for this plugin.  I take it a fresh install of the OS with i686 packages would work, but the downtime is too great for your clients.

I am curious of the output of the equivalent of the ```yum replace``` command.

**Comment by LewisR** [comment]
I have to tone down my normal logging verbosity, as there is a lot of excess reported...

Okay, changing my own platform from pentium4 to i686, debuglevel 4, I get the following:

```
[j:\usr\sbin]yum replace binutils --replace-with binutils
Loaded plugins: downloadonly, replace, verify, versionlock
Config time: 0.127
Yum Version: 3.4.3
Setting up Package Sacks
arcanoae-exp         | 1.9 kB  00:00
arcanoae-rel         | 1.9 kB  00:00
netlabs-exp          | 2.9 kB  00:00
netlabs-exp/primary_ | 211 kB  00:01       ]  87 kB/s | 180 kB  00:00 ETA
netlabs-rel          | 2.9 kB  00:00
netlabs-rel/primary_ | 1.3 MB  00:06     =-] 166 kB/s | 1.3 MB  00:00 ETA
Reading version lock configuration
pkgsack time: 14.938
rpmdb time: 0.019
Replacing packages takes time, please be patient...
Building updates object
up:Obs Init time: 0.304
up:simple updates time: 0.037
up:obs time: 0.000
up:condense time: 0.000
updates time: 0.421
Resolving Dependencies
--> Running transaction check
---> Package binutils.i686 0:2.27-2.oc00 will be installed
---> Package binutils.pentium4 0:2.27-2.oc00 will be erased
--> Finished Dependency Resolution
Dependency Process ending
Depsolve time: 0.449

Dependencies Resolved

================================================================================

 Package         Arch            Version               Repository          Size
================================================================================

Installing:
 binutils       (B i686            2.27-2.oc00           netlabs-rel        6.0
M
Removing:
 binutils        pentium4        2.27-2.oc00           installed           12 M

Transaction Summary
================================================================================

Install       1 Package
Remove        1 Package

Total size: 6.0 M
Is this ok [y/N]: y
Downloading Packages:
using local copy of binutils-2.27-2.oc00.i686
Removing Package binutils-2.27-2.oc00.pentium4
Adding Package binutils-2.27-2.oc00.i686 in mode u
Running Transaction Check
Transaction Check time: 0.068
Running Transaction Test
Transaction Test Succeeded
Transaction Test time: 3.074
Running Transaction
  Installing : binutils-2.27-2.oc00.i686                                    1/2

  Cleanup    : binutils-2.27-2.oc00.pentium4                                2/2

VerifyTransaction time: 0.338
Transaction time: 8.794

Removed:
  binutils.pentium4 0:2.27-2.oc00


Installed:
  binutils.i686 0:2.27-2.oc00


Complete!
```

Is there something (with a higher debug level) which you would be more interested in seeing?

**Comment by LewisR** [comment]
I should note that the <(B> is cosmetic and appears from time to time in some messages output by our implementation.

**Comment by b-harper** [comment]
@LewisR, I now understand the issue and I got some good news and bad news.

Good news: I am seeing the same behavior in EL as you are seeing in OS/2.
Bad news:  Fixing this issue is not the highest of priorities for us at this moment.  Sure, it should get fixed, but it is just hard to prioritize it when it works via yum.

**Comment by LewisR** [comment]
@b-harper - Understood entirely, and thanks for all of the back and forth here. If you could just provide a pointer for me as to where to look, I'm happy to take a stab at this, myself.

**Comment by LewisR** [comment]
@andytson - I tried rolling back your EL5 changes, but to no avail - almost. From the python prompt, I can actually import replace without error, but print doesn't show it loaded.

Scratch that: It's the same behavior as before. If I add yum-plugins to PYTHONPATH, the behavior is the same with or without importing/calling checkEnabledRepo (that was your change in 2014 for EL5, according to the log).

**Comment by andytson** [comment]
sorry, you interpreted my response incorrectly. I never made changes to support EL5 (only a bugfix for some code I'd added), only I spotted there was some EL5 compatibility that I think is possibly the cause (as for most intents and purposes a plugin that hooks into yum in a different way to other plugins could be the reason for the issue).

On another note, Chef also has issues with yum when yum-plugin-replace is installed. Chef uses a yum-dump script to get metadata out that it can parse. However it has some functionality in that disables plugins that don't work, so it doesn't error and can continue.

I expect the reason it throws a warning also to be for the same reason.

**Comment by LewisR** [comment]
Ah, sorry about that. You are correct; I mistook your comment, coupled with a diff, to mean that removing that import resolved the issue. I thought that was rather simplistic... ;-)

Perhaps the same issue applies to downloadonly and verify, as I mentioned above. I'll have to look at the code for those to see if anything stands out to me. I'm not a Python wiz, so it generally takes me a little while to digest what I'm reading and try to sort out the code paths in my head, but perhaps a pattern will emerge.

Thanks.

**Comment by andytson** [comment]
If this helps, I've had a hack of the file to see what lines cause it to not list in the `yb.plugins._plugins` and see:

This line is causing the `Plugin "replace" can't be imported` message:
https://github.com/iuscommunity/yum-plugin-replace/blob/master/lib/yum-plugins/replace.py#L27

TYPE_INTERACTIVE here is stopping it from showing in the _plugins list
https://github.com/iuscommunity/yum-plugin-replace/blob/master/lib/yum-plugins/replace.py#L30

If removing TYPE_INTERACTIVE, parser is null here, giving error `'NoneType' object has no attribute 'add_option'`
https://github.com/iuscommunity/yum-plugin-replace/blob/master/lib/yum-plugins/replace.py#L39

**Comment by andytson** [comment]
so in summary, I think you need to trigger a few more yum internals before the plugin can be imported, and added as an interactive plugin

**Comment by LewisR** [comment]
We're experimenting with reimplementing this functionality in a way which works better for our frontend. Try as I might, I could not get enough background going to get this plugin to load properly in this manner.

Thanks for the great suggestions and back and forth. Much appreciated.
